repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.9.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-byte-order-marker

  - repo: local
    hooks:
      - id: csv-header-lock
        name: csv header lock
        entry: python -m keeper_auto.template --lint
        language: system
        pass_filenames: true
        files: ^perms/.*\.csv$
